### ISSUE TITLE
vgg16_pretrained_features.pth

### ISSUE THREAD

**Issue by yanx27** [Lotayou/everybody_dance_now_pytorch#1]
Could you provide vgg16_pretrained_features.pth when we train the face enhancement net? Thank you very much!

**Comment by yanx27** [comment]
or could you provided final_generator.pth for us to test

**Comment by Lotayou** [comment]
Thanks for the feedback. The pre-trained models are too large and cannot be directly uploaded into github repo. I have uploaded them on Yandex Disk and updated links in readme.md. 

I'm gonna close this issue for now. If you find any problem when using my model, feel free to leave me a  message any time.
