### ISSUE TITLE
Is it possible to generate frame using OpenPose coordinates?

### ISSUE THREAD

**Issue by talatccan** [Lotayou/everybody_dance_now_pytorch#11]
Hi,

I trained my model and its working well with the test videos/frames.
Now, my purpose is generate frames using OpenPose coordinates. I will give the coordinates and will get the output frame. Is it possible? And if its, how can i do that?

**Comment by Lotayou** [comment]
It's possible, just convert the coordinates into stick-figure images and use that for input.
