### ISSUE TITLE
Output video performance

### ISSUE THREAD

**Issue by kai0122** [Lotayou/everybody_dance_now_pytorch#19]
Hello,

I tried to run your code on my test dataset, given a target pose and a source image.
However, the generated video does not look like the source image at all.
The problem is that it looks like the dancing video that you show as a demo in the Afrobeat workout Sequence from YouTube.
Is this normal?

Thank you

**Comment by Lotayou** [comment]
It is normal if you used my pretrained Afrobeat model on other videos. This model has very weak generalization ability towards unseen persons.
The technique used in this repo is quite obsolete now.  You can refer to more advanced fewshot vid2vid work
