### ISSUE TITLE
no module named draw_pose_from_coords in compute_coordinates_for_video.py

### ISSUE THREAD

**Issue by 7color94** [Lotayou/everybody_dance_now_pytorch#2]
Could you tell me where is the function draw_pose_from_coords ?

**Comment by Lotayou** [comment]
It's defined in `./pose-estimator/pose_utils.py`.

**Comment by 7color94** [comment]
Sorry, you made a spelling error in "draw_pose_from_coords"  (The correct one is draw_pose_from_cords)?
And, how many epochs and batch size in your training ? The total epochs are 100 and the batch size is 1 ?

**Comment by 7color94** [comment]
Sorry, you made a spelling error in "draw_pose_from_coords" (The correct one is draw_pose_from_cords)?
And, how many epochs and batch size in your training ? The total epochs are 200 and the batch size is 1 ? And it will take too long time for training in a 3-4 mins video (totally 5000 frames).

**Comment by 7color94** [comment]
And did you do the data augmentation (e.g. random crop/scale) during the pix2pix training ?

**Comment by Lotayou** [comment]
Thanks for notice, the typo is now fixed.
The batch size I use is 1, but each batch contains two consecutive frames (and corresponding pose stick figures), so the memory cost is huge, on my machine any batch size larger than 1 leads to OOM. As for the epochs, normally 30 epochs would be enough for visually pleasing videos, which takes about 2 days. I use 10000 frames for training, so in your case 1 day should be enough. However I don't know if 5000 frames are adequate, feel free to show me your result.
Also, I didn't do random cropping/scaling, as this would break temporal consistency. The current implemetation does not hold well for large scale variations. Please refer to `Try your own dataset` section in readme for more tips.
