### ISSUE TITLE
Not have NVIDIA card

### ISSUE THREAD

**Issue by AbdulBariKhan** [Lotayou/everybody_dance_now_pytorch#6]
Can this code run without using CUDA.

**Comment by Lotayou** [comment]
It can, but will take you ages to train the network... If you insist, just deploy the model on CPU device with `torch.device('cpu')`

**Comment by AbdulBariKhan** [comment]
Will it work? And where to deploy with torch.device('cpu')

**Comment by AbdulBariKhan** [comment]
Please let me know.
