### ISSUE TITLE
compute_coordinates_for_video.py error

### ISSUE THREAD

**Issue by seijihirosawa** [Lotayou/everybody_dance_now_pytorch#9]
Hi! Thank you for your great job!
I have two questions.

1.When I try to run "compute_coordinates_for_video.py" after creating the dataset, I get the following error:

File "./pose_estimator/compute_coordinates_for_video.py", line 248
    if nor os.path.isdir(pose_dir):

Is "If not" correct??

2.I have also another error below.
File "./pose_estimator/compute_coordinates_for_video.py", line 260
    cord = cordinates_from_image_file(img, model=model)
       ^
SyntaxError: invalid syntax

The dataset directory is set as follows.
img_dir = './datasets/train_B'

Could you let me know how I resolve error?

Thanks

**Comment by FanaticKyo** [comment]
I think line 259 is missing a right parenthesis.
